#!/usr/bin/env bash
IMG=$1

if [[ $GC_PROJECTID == "" ]]; then
  echo "You need to specify an Google Cloud Project ID through GC_PROJECTID variable"
  exit
fi

if [[ $IMG == "" ]]; then
  echo "You need to specify an image name"
  exit
fi

docker tag ${IMG} gcr.io/${GC_PROJECTID}/${IMG}
docker push gcr.io/${GC_PROJECTID}/${IMG}
echo "Done!"
