#!/usr/bin/env bash
COMMAND=$1
DOTFILES="$HOME/.onhernandes/dotfiles"

ensure_symlink() {
  if [[ ! -f $2 ]]; then
    ln -s $1 $2
  fi
}

if [[ $COMMAND == "python" ]]; then
  pip install --user neovim powerline-shell flake8 black
  exit
fi

if [[ $COMMAND == "clear-desktop" ]]; then
  while true; do
      read -p "You really wanna clear all your desktop? " yn
      case $yn in
          [Yy]* ) rm -rf $HOME/Desktop/* && echo "Desktop cleared"; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no.";;
      esac
  done
  exit
fi

if [[ $COMMAND == "symlink" ]]; then
  chmod +x $DOTFILES/commands/r
  chmod +x $DOTFILES/commands/subl-snippet

  ensure_symlink $DOTFILES/git/gitconfig $HOME/.gitconfig
  ensure_symlink $DOTFILES/git/gitconfig /etc/.gitconfig
  ensure_symlink $DOTFILES/git/gitignore_global $HOME/.gitignore_global
  ensure_symlink $DOTFILES/git/gitignore_global /etc/.gitignore_global
  ensure_symlink $DOTFILES/vimrc $HOME/.config/nvim/init.vim
  ensure_symlink $DOTFILES/tmux.conf $HOME/.tmux.conf
  ensure_symlink $DOTFILES/commands/r /usr/bin/r
  ensure_symlink $DOTFILES/commands/subl-snippet /usr/bin/subl-snippet
  exit
fi

echo "Available commands: python | clear-desktop | symlink"

