#!/usr/bin/env bash
COMMAND=$1
DOTFILES="$HOME/.onhernandes/dotfiles"

ensure_symlink() {
  if [[ ! -f $2 ]]; then
    ln -s $1 $2
  fi
}

if [[ $COMMAND == "pip" ]]; then
  $DOTFILES/setup/pip-packages
  exit
fi

if [[ $COMMAND == "npm" ]]; then
  $DOTFILES/setup/npm-packages
  exit
fi

if [[ $COMMAND == "yaourt" ]]; then
  $DOTFILES/setup/manjaro/yaourt
  exit
fi

if [[ $COMMAND == "pacman" ]]; then
  $DOTFILES/setup/manjaro/pacman
  exit
fi

if [[ $COMMAND == "symlink" ]]; then
  $DOTFILES/setup/manjaro/symlinks
  exit
fi

if [[ $COMMAND == "clear-desktop" ]]; then
  while true; do
      read -p "You really wanna clear all your desktop? " yn
      case $yn in
          [Yy]* ) rm -rf $HOME/Desktop/* && echo "Desktop cleared"; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no.";;
      esac
  done
  exit
fi
