#!/usr/bin/bash

NOTION_API_KEY=$NOTION_API_KEY
DATABASE_ID=$DATABASE_ID

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  printf "✨ Welcome! Thanks for using this script! ✨\n\n"
  printf "⏳ The time format⏰: HH:mm e.g. 14:30, 09:00, 10:13, 19:44, etc⏳\n"
  printf "⏳This format is applied as: date --iso-8601=seconds --date=<start time, 13:40>⏳\n\n"
  printf "🎩 Usage:\n\n"
  printf "\twork-schedule <time you started working> <time you ended working>\n"
  exit
fi

START_TIME=$1
START_DATETIME=$(date --iso-8601=seconds --date=$START_TIME)

END_TIME=$2
END_DATETIME=$(date --iso-8601=seconds --date=$END_TIME)


curl 'https://api.notion.com/v1/pages' \
  -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
  -H "Content-Type: application/json" \
  -H "Notion-Version: 2021-08-16" \
  --data '{
    "parent": { "database_id": "'"$DATABASE_ID"'" },
        "properties": {
                "ignore-me": {
                        "title": [
                                {
                                        "text": {
                                                "content": ""
                                        }
                                }
                        ]
                },
                "Data e hora de entrada": {
      "date": { "start": "'"$START_DATETIME"'", "end": null }
                },
                "Data e hora de saída": {
      "date": { "start": "'"$END_DATETIME"'", "end": null }
                }
        },
        "children": []
}'
