#!/bin/bash

DOTFILES=$HOME/.onhernandes/dotfiles

if [[ ! -d $HOME/.onhernandes ]]; then
    mkdir $HOME/.onhernandes
fi

if ! git_cmd="$(type -p "git")" || [[ -z $git_cmd ]]; then
  pacman -S --noconfirm git
fi

if [[ ! -d $DOTFILES ]]; then
  git clone git@github.com:onhernandes/dotfiles.git $DOTFILES
fi
