#!/bin/bash

DOTFILES=$HOME/.onhernandes/dotfiles

if [[ ! -d $HOME/.onhernandes ]]; then
    mkdir $HOME/.onhernandes
fi

if ! git_cmd="$(type -p "git")" || [[ -z $git_cmd ]]; then
  pacman -S --noconfirm git
fi

if [[ ! -d $HOME/.ssh ]] || [[ ! -e $HOME/.ssh/id_rsa.pub ]]; then
  ssh-keygen
fi

echo \n\n
cat $HOME/.ssh/id_rsa.pub
echo "After logging on Github, run "
echo "curl https://raw.githubusercontent.com/onhernandes/dotfiles/master/setup/create-dotfiles | sh"
