#!/bin/bash

SETUP_DIR=$HOME/.onhernandes/dotfiles/setup
DOTFILES=$HOME/.onhernandes/dotfiles

if [[ ! -d $DOTFILES ]]; then
  mkdir ~/.onhernandes
  git clone git@github.com:onhernandes/dotfiles.git $DOTFILES
fi

# Install pamac packages
PAMAC_PACKAGES="universal-ctags openssh docker docker-compose curl arandr autorandr xclip xf86-input-synaptics fzf ruby neovim cmake freetype2 fontconfig pkg-config make rustup powerline-fonts kitty tmux firefox-developer-edition kubectl shfmt telegram-desktop python2-pip htop bat the_silver_searcher asdf-vm android-studio watchman google-chrome tmuxinator"
sudo pamac install --no-confirm $PAMAC_PACKAGES
# sudo pamac build --no-confirm google-chrome

# Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

source $HOME/.bashrc
nvm install 12

# Install snap packages
sudo snap install spotify

# Install NPM Packages
$SETUP_DIR/npm-packages

# Install pip packages
$SETUP_DIR/pip-packages

# Install ruby gems
$SETUP_DIR/ruby-gems

# Set up symlinks
$SETUP_DIR/symlinks

# Install Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Downloads tmuxinator auto-completion for bash
wget https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.bash -O $HOME/.tmuxinator.bash

echo "source $HOME/.onhernandes/dotfiles/bashrc" >> $HOME/.bashrc
source $HOME/.bashrc

# Install java asdf plugin
echo "Installing openjdk-14, recommended by React Native"
asdf plugin-add java https://github.com/halcyon/asdf-java.git
asdf install java openjdk-14
asdf global java openjdk-14

echo "Done"
