#!/usr/bin/bash
DOTFILES="${HOME}/.onhernandes/dotfiles"

if [[ ! -e ${HOME}/.gitconfig ]]; then
  ln -s ${DOTFILES}/git/gitconfig ${HOME}/.gitconfig
fi        

if [[ ! -e ${HOME}/.config/nvim ]]; then
  ln -s $DOTFILES/neovim $HOME/.config/nvim
fi

if [[ ! -d $HOME/.tmux ]]; then
  mkdir -p $HOME/.tmux/plugins
fi 

if [[ ! -e ${HOME}/.config/.flake8 ]]; then
  ln -s $DOTFILES/python/flake8 $HOME/.config/.flake8
fi

if [[ ! -e ${HOME}/.tmux.conf ]]; then
  ln -s $DOTFILES/tmux.conf ${HOME}/.tmux.conf
fi

if [[ ! -e ${HOME}/.czrc ]]; then
  ln -s $DOTFILES/czrc ${HOME}/.czrc
fi

if [[ ! -f ${HOME}/.tmuxinator.bash ]]; then
  curl https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.bash -o $HOME/.tmuxinator.bash
fi

if [[ ! -f ${HOME}/.git-completion.bash ]]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o $HOME/.git-completion.bash
fi

# powerline config
if [[ ! -d $HOME/.config/powerline-shell ]]; then
  mkdir $HOME/.config/powerline-shell
fi                             

if [[ ! -e ${HOME}/.config/powerline-shell/config.json ]]; then
  ln -s $DOTFILES/powerline.json $HOME/.config/powerline-shell/config.json
fi
