#!/usr/bin/bash

SETUP_DIR="${HOME}/.onhernandes/dotfiles/setup"

$SETUP_DIR/manjaro/pacman
$SETUP_DIR/manjaro/yaourt

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

source $HOME/.bashrc
nvm install 10
nvm alias default 10

$SETUP_DIR/npm-packages

curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
sudo python /tmp/get-pip.py
source $HOME/.bashrc
rm /tmp/get-pip.py

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

$SETUP_DIR/pip-packages
$SETUP_DIR/ruby-gems
$SETUP_DIR/manjaro/symlinks

echo "source $HOME/.onhernandes/dotfiles/bashrc" >> $HOME/.bashrc

source $HOME/.bashrc
