#!/usr/bin/bash

PACMAN_PACKAGES="openssh docker docker-compose curl easytag arandr autorandr xclip xf86-input-synaptics fzf ruby neovim cmake freetype2 fontconfig pkg-config make rustup powerline-fonts"
pacman -S --noconfirm $PACMAN_PACKAGES
